services:
  postgres:
    image: postgres:17
    container_name: db-app
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db

    volumes:
      - ./postgres_data:/var/lib/postgresql/data